### ISSUE TITLE
.github/workflows: Enable terraform-provider-corner acceptance testing in CI

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-go#187]
### terraform-plugin-go version

```
v0.9.0
```

### Use cases

Changes like #185 can be a little nerve-racking, since they affect the underlying plugin handshake. To gain more confidence in these, we should enable [`terraform-provider-corner`](https://github.com/hashicorp/terraform-provider-corner) acceptance testing in CI, similar to the downstream terraform-plugin-framework and terraform-plugin-sdk repositories.

### Proposal

Add something like the below to `.github/workflows/ci-go.yml`:

```yaml
  terraform-provider-corner:
    defaults:
      run:
        working-directory: terraform-provider-corner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: terraform-provider-corner
          repository: hashicorp/terraform-provider-corner
      - id: go-version
        # Reference: https://github.com/actions/setup-go/issues/23
        run: echo "::set-output name=version::$(cat ./.go-version)"
        working-directory: .
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - run: go mod edit -replace=github.com/hashicorp/terraform-plugin-go=../
      - run: go mod tidy
      - run: go test -v ./...
        env:
          TF_ACC: '1'
```
